parameters:
 N: 100000     # uint64_t, Number of points
 L: 20.0       # double, X-Y border
 r: 1.0        # double, Circle radius
 sigma: 0.05   # double, Circle depth
 q: 3          # uint16_t, Number of colors
 energy: 0.0   # double, Start energy

# histogram output filename prefix
 histogram_filename_prefix: "histogram"
# postfix without '.'
 histogram_filename_postfix: "dat"
